#! /bin/sh

bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor HDMI2 -d 6 7 8 9

bspc config border_width       1
bspc config window_gap         6
bspc config split_ratio        0.52
bspc config borderless_monocle true
bspc config gapless_monocle    true
# bspc config pointer_modifier    super

# rules
bspc rule -a Gimp     desktop=^5 follow=on floating=on
bspc rule -a mplayer2 state=floating
bspc rule -a mpv      state=floating
bspc rule -a ncmpcpp  state=floating
bspc rule -a zathura  state=tiled
bspc rule -a emacs    state=tiled
bspc rule -a feh      state=pseudo_tiled
# colors

bspc config active_border_color   '#ffc47a'
bspc config focused_border_color  '#bee3f3'
bspc config normal_border_color   '#002211'
bspc config presel_feedback_color '#31aeff'
bspc config urgent_border_color   '#da332d'

# bspc config active_locked_border_color      '#ff9e24'
# bspc config focused_locked_border_color     '#ff9e24'
# bspc config normal_locked_border_color      '#31aeff'

# start panel
polybar-multimon


# For some reason polybar resets the top_padding.
# Therefore, we reset top_padding after polybar started
bspc config top_padding 18
